### ISSUE TITLE
Anyone can see the list of student ID's

### ISSUE THREAD

**Issue by drohrbaugh9** [Haley-Kubala/Senior-Design-Project#8]
I just realized this, but anyone can see the list of student ID's we have in this repository. If we need to make a private repository to hold the student ID's, I can do that. It is most likely that no one else besides us and a few trustworthy people at HPE even know of this file, but all the same... I do think that the file is germane to this project, but it is, in my opinion, too accessible.

**Comment by Haley-Kubala** [comment]
Okay, yeah go ahead and change it
